"""
Project Euler Problem 002: https://projecteuler.net/problem=2

Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def solution(limit: int = 4000000) -> int:
    """
    Returns the sum of even valued Fibonacci terms, up to the limit

    >>> solution(10)
    10
    >>> solution(15)
    10
    >>> solution(2)
    2
    >>> solution(1)
    0
    >>> solution(34)
    44
    """
    if limit < 2:
        return 0
    fib_sequence = [1, 2]
    even_fib_sequence = [2]
    while fib_sequence[-1] <= limit:
        new_number = fib_sequence[-1] + fib_sequence[-2]
        if new_number > limit:
            break
        fib_sequence.append(new_number)
        if new_number % 2 == 0:
            even_fib_sequence.append(new_number)

    return sum(even_fib_sequence)


if __name__ == "__main__":
    print(f"{solution() = }")
